name: Your New Jekyll Site
description: Developer
meta_description: "Jekyll Site, Blogging"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /jekyllblog
domain_name: 'http://hieu2014.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://hieu2014.github.io/jekyllblog/'
author:         'Hieu Tran'
